name: Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - uses: pnpm/action-setup@master
        with:
          version: latest
      - uses: Hedgehog-Computing/github-token-action@latest
        with:
          registry: true
      - run: yarn install
      - run: yarn run build
      - name: Publish to GitHub Package
        run: ./scripts/publish-to-github.sh
